{
  "openapi": "3.0.1",
  "info": {
    "title": "Rekenen",
    "description": "Berekeningen maken",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/kwadraat/{getal}": {
      "get": {
        "tags": [
          "kwadraat-controller"
        ],
        "summary": "het kwadraat van een getal",
        "operationId": "kwadraat",
        "parameters": [
          {
            "name": "getal",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "integer",
                  "format": "int32"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {

  }
}